; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "RCS.ASBUILT"
#define MyAppVersion "1.5"
#define MyAppPublisher "BANKS&BANKS"
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MyProg-x64.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{14F018FE-E07A-42CC-B8E0-E484AEE93A7A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=mysetup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\SymbolsLibrary\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\docs\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\Subdivision-Mock\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\.gitattributes"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\.gitignore"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\ALL.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\all_commands.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\crashlog.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\crashlog_ascii.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\curves_and_rkrk_test.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\demo_piping.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\demo_points.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\dxf_10.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\dxf_points.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\EAST.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\EPANET.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\error_test.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\export_rules.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\extract_dxf.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\extract_excel.ps1"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\extracted.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\fig_curves_test.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\GasElectricStormCodes.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\gen_script.cs"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\generate_excel.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\JEA_Validation_List.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\MasterUtilityCodes.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\north.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\OutputLog.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\parse_dxf_layers.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\PipingNetwork.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\PipingScript.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\PipingScript2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\Project.dxf"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\ProjectPoints_Export.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\ProjectSchedule.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\RCS.Cogo.Enterprise.Modern.sln"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\RCS_TestPoints_Utilities.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\RCS_TestPoints_Utilities_ALLCODES.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\RCS_TestPoints_Utilities_ALLCODES_FULLDESC (1).txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\reset_db.bat"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\reverse_curves_test.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\robust_test.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\schema.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\showcase_network.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\SOUTH.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\Subdivision_Integrated_Design.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\Subdivision_Water_Design.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\temp_dxf.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_COGO_SCRIPT-1.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_COGO_SCRIPT-1_ascii.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_COGO_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_DATA_SCRIPT.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_ELECTRIC_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_GAS_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\test_geom.cogo"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_PIPING_SCRIPT.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_POINTS_SCRIPT.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_SEWER_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_STORM_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_SYMBOLS_SCRIPT.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_WASTE_WATER_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\TEST_WATER_V2.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\USER_MANUAL_AND_TESTING_GUIDE.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\utility_codes_master.csv"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\utility_codes_master.xls.xlsx"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\UtilitySymbols_Mapping.xlsx"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\utils_gen_cogo.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\utils_gen_scripts.py"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\validation_rules.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\validation_rules_dump.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\water_sewer.pipe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\Water_System_Script.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Daryl Banks\source\repos\RCS.Cogo.Enterprise.Modern\xc_test.cogo"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

