<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RCS.Cogo.Core\RCS.Cogo.Core.csproj" />
    <ProjectReference Include="..\RCS.Geo.Abstractions\RCS.Geo.Abstractions.csproj" />
    <ProjectReference Include="..\RCS.Geo.Core\RCS.Geo.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

