import datetime
import math

class LandXmlWriter:
    @staticmethod
    def generate_landxml(project_name: str, pipes: list, structures: list, engine) -> str:
        """
        Generates LandXML version 1.2 compliant layout strings representing
        points, parcels, alignments, sewer structures, and pipe networks.
        """
        date_str = datetime.date.today().isoformat()
        
        xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<LandXML xmlns="http://www.landxml.org/schema/LandXML-1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.landxml.org/schema/LandXML-1.2 http://www.landxml.org/schema/LandXML-1.2/LandXML-1.2.xsd" date="{date_str}" time="12:00:00" version="1.2">
  <Project name="{project_name}" desc="Generated by BoundaryQC Python Engine" />
  <Units>
    <Imperial areaUnit="squareFoot" linearUnit="foot" volumeUnit="cubicYard" temperatureUnit="fahrenheit" pressureUnit="inHG"/>
  </Units>
"""

        # 1. Add Alignments (Open figures)
        alignments_xml = ""
        for fig in engine.figures.values():
            if not fig.point_ids:
                continue
            is_closed = len(fig.point_ids) >= 3 and fig.point_ids[0] == fig.point_ids[-1]
            if not is_closed:
                alignments_xml += f'    <Alignment name="{fig.name}">\n      <CoordGeom>\n'
                for i in range(len(fig.point_ids) - 1):
                    p1 = engine.get_point(fig.point_ids[i])
                    p2 = engine.get_point(fig.point_ids[i+1])
                    if p1 and p2:
                        alignments_xml += f'        <Line>\n          <Start>{p1.northing:.2f} {p1.easting:.2f}</Start>\n          <End>{p2.northing:.2f} {p2.easting:.2f}</End>\n        </Line>\n'
                alignments_xml += '      </CoordGeom>\n    </Alignment>\n'
        if alignments_xml:
            xml += f"  <Alignments>\n{alignments_xml}  </Alignments>\n"

        # 2. Add CgPoints (Coordinate points)
        if engine.points:
            xml += "  <CgPoints>\n"
            for pt_id, (pt, desc) in engine.points.items():
                xml += f'    <CgPoint name="{pt_id}" desc="{desc}">{pt.northing:.2f} {pt.easting:.2f} {pt.elevation:.2f}</CgPoint>\n'
            xml += "  </CgPoints>\n"

        # 3. Add Parcels (Closed figures)
        parcels_xml = ""
        for fig in engine.figures.values():
            if not fig.point_ids:
                continue
            is_closed = len(fig.point_ids) >= 3 and fig.point_ids[0] == fig.point_ids[-1]
            if is_closed:
                parcels_xml += f'    <Parcel name="{fig.name}">\n      <CoordGeom>\n'
                for i in range(len(fig.point_ids) - 1):
                    p1 = engine.get_point(fig.point_ids[i])
                    p2 = engine.get_point(fig.point_ids[i+1])
                    if p1 and p2:
                        parcels_xml += f'        <Line>\n          <Start>{p1.northing:.2f} {p1.easting:.2f}</Start>\n          <End>{p2.northing:.2f} {p2.easting:.2f}</End>\n        </Line>\n'
                parcels_xml += '      </CoordGeom>\n    </Parcel>\n'
        if parcels_xml:
            xml += f"  <Parcels>\n{parcels_xml}  </Parcels>\n"

        # 4. Add PipeNetworks
        if pipes or structures:
            xml += """  <PipeNetworks>
    <PipeNetwork name="Network-1">
      <Structs>
"""
            # Add structures
            for s in structures:
                desc = getattr(s, 'type', 'Manhole') or 'Manhole'
                pt = engine.get_point(s.point_id)
                northing = pt.northing if pt else 0.0
                easting = pt.easting if pt else 0.0
                invert = pt.elevation if pt else 0.0
                xml += f"""        <Struct name="{s.id}" desc="{desc}">
          <Center>{northing:.2f} {easting:.2f}</Center>
          <Invert elev="{invert:.2f}"/>
        </Struct>\n"""

            xml += "      </Structs>\n      <Pipes>\n"

            # Add pipes
            for p in pipes:
                p1 = engine.get_point(p.from_point_id)
                p2 = engine.get_point(p.to_point_id)
                
                length = 0.0
                if p1 and p2:
                    length = math.sqrt((p2.easting - p1.easting) ** 2 + (p2.northing - p1.northing) ** 2)
                
                material = getattr(p, 'material', 'PVC') or 'PVC'
                diameter = getattr(p, 'diameter', 8)
                start_str = f' refStart="{p.from_point_id}"' if getattr(p, 'from_point_id', None) else ''
                end_str = f' refEnd="{p.to_point_id}"' if getattr(p, 'to_point_id', None) else ''
                
                xml += f"""        <Pipe name="{p.id}" length="{length:.2f}" desc="{material}"{start_str}{end_str}>
          <PipeFlow state="steady"/>
          <Feature>
            <Property label="diameter" value="{diameter}"/>
          </Feature>
        </Pipe>\n"""

            xml += """      </Pipes>
    </PipeNetwork>
  </PipeNetworks>\n"""

        xml += "</LandXML>"
        return xml
