<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RCS.Cogo.Core\RCS.Cogo.Core.csproj" />
    <ProjectReference Include="..\RCS.Cogo.App\RCS.Cogo.App.csproj" />
    <ProjectReference Include="..\RCS.Piping.Core\RCS.Piping.Core.csproj" />
    <ProjectReference Include="..\RCS.Services\RCS.Services.csproj" />
    <ProjectReference Include="..\RCS.Data\RCS.Data.csproj" />
    <Content Include="validation_rules.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RCS.Cogo.AI\RCS.Cogo.AI.csproj" />
    <ProjectReference Include="..\RCS.Alignments.Core\RCS.Alignments.Core.csproj" />
    <ProjectReference Include="..\RCS.Geo.Wpf\RCS.Geo.Wpf.csproj" />
    <ProjectReference Include="..\RCS.Geo.ProjNet\RCS.Geo.ProjNet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="EPPlus" Version="7.6.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
