// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCS.Data;

#nullable disable

namespace RCS.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314032935_AddSizeSecondary")]
    partial class AddSizeSecondary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("RCS.Data.Entities.AppGlobalSetting", b =>
                {
                    b.Property<string>("SettingKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SettingKey");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("RCS.Data.Entities.ChilledLocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ChilledLocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.CogoCodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Block")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CogoCodes");
                });

            modelBuilder.Entity("RCS.Data.Entities.ELocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ELocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.Figure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Layer");

                    b.HasIndex("ProjectId");

                    b.ToTable("Figures");
                });

            modelBuilder.Entity("RCS.Data.Entities.FigureVertex", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Bulge")
                        .HasColumnType("REAL");

                    b.Property<string>("FigureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PointId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FigureId");

                    b.HasIndex("PointId");

                    b.ToTable("FigureVertices");
                });

            modelBuilder.Entity("RCS.Data.Entities.Fitting", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Fittings");

                    b.HasDiscriminator().HasValue("Fitting");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RCS.Data.Entities.GLocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("GLocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.MaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("RCS.Data.Entities.Meter", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Meters");

                    b.HasDiscriminator().HasValue("Meter");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RCS.Data.Entities.PartSpecificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Deflection")
                        .HasColumnType("REAL");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<double?>("NominalDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PipeThickness")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("PartSpecifications");
                });

            modelBuilder.Entity("RCS.Data.Entities.Pipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Diameter")
                        .HasColumnType("REAL");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<double?>("EastingEnd")
                        .HasColumnType("REAL");

                    b.Property<double?>("EastingStart")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<double?>("InvertEnd")
                        .HasColumnType("REAL");

                    b.Property<double?>("InvertStart")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NorthingEnd")
                        .HasColumnType("REAL");

                    b.Property<double?>("NorthingStart")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Pipes");

                    b.HasDiscriminator().HasValue("Pipe");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RCS.Data.Entities.PipeCrossing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("PipeCrossings");
                });

            modelBuilder.Entity("RCS.Data.Entities.ProjectEntity", b =>
                {
                    b.Property<string>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("ProjectNumber");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedHydrant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ReclaimedHydrants");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedLocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ReclaimedLocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.STLocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("STLocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.Structure", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Structures");

                    b.HasDiscriminator().HasValue("Structure");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RCS.Data.Entities.SurveyPoint", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<double>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("PointNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("SurveyPoints");
                });

            modelBuilder.Entity("RCS.Data.Entities.SymbolManagerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("ClientCode");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT")
                        .HasColumnName("Discipline");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT")
                        .HasColumnName("Symbol");

                    b.Property<string>("SystemCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("SystemCode");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("SymbolManager");
                });

            modelBuilder.Entity("RCS.Data.Entities.ValidationRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ValidationRules");
                });

            modelBuilder.Entity("RCS.Data.Entities.Valve", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Valves");

                    b.HasDiscriminator().HasValue("Valve");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RCS.Data.Entities.WWLocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WWLocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterHydrant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WaterHydrants");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterLocateBox", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("AdjustedInvert")
                        .HasColumnType("REAL");

                    b.Property<string>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discipline")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Easting")
                        .HasColumnType("REAL");

                    b.Property<double?>("Elevation")
                        .HasColumnType("REAL");

                    b.Property<string>("FacilityOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureType")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InnerDiameter")
                        .HasColumnType("REAL");

                    b.Property<string>("LiningManufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("LiningMaterial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Northing")
                        .HasColumnType("REAL");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<double?>("OuterWallThicknessTop")
                        .HasColumnType("REAL");

                    b.Property<string>("PartKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PipeClass")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Size")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeSecondary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSheetRowIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtype")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TopOutsideWallElev")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warning")
                        .HasColumnType("TEXT");

                    b.Property<string>("YearManufactured")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WaterLocateBoxes");
                });

            modelBuilder.Entity("RCS.Data.Entities.ChilledFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("ChilledFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.EFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("EFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.GFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("GFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("ReclaimedFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.STFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("STFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.WWFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("WWFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterFitting", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Fitting");

                    b.HasDiscriminator().HasValue("WaterFitting");
                });

            modelBuilder.Entity("RCS.Data.Entities.ChilledMeter", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Meter");

                    b.HasDiscriminator().HasValue("ChilledMeter");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedMeter", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Meter");

                    b.HasDiscriminator().HasValue("ReclaimedMeter");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterMeter", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Meter");

                    b.HasDiscriminator().HasValue("WaterMeter");
                });

            modelBuilder.Entity("RCS.Data.Entities.ChilledPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("ChilledPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.EGravityPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("EGravityPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.EPressurePipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("EPressurePipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.GGravityPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("GGravityPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.GPressurePipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("GPressurePipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("ReclaimedPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.STGravityPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("STGravityPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.STPressurePipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("STPressurePipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.WWGravityPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("WWGravityPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.WWPressurePipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("WWPressurePipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterPipe", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Pipe");

                    b.HasDiscriminator().HasValue("WaterPipe");
                });

            modelBuilder.Entity("RCS.Data.Entities.ChilledPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("ChilledPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.EManhole", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("EManhole");
                });

            modelBuilder.Entity("RCS.Data.Entities.EPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("EPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.EServicePoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("EServicePoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.GManhole", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("GManhole");
                });

            modelBuilder.Entity("RCS.Data.Entities.GPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("GPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.GServicePoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("GServicePoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.Manhole", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("Manhole");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("ReclaimedPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.STManhole", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("STManhole");
                });

            modelBuilder.Entity("RCS.Data.Entities.STPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("STPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.STServicePoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("STServicePoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.WWPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("WWPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.WWServicePoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("WWServicePoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterPoint", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Structure");

                    b.HasDiscriminator().HasValue("WaterPoint");
                });

            modelBuilder.Entity("RCS.Data.Entities.ChilledValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("ChilledValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.EValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("EValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.GValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("GValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.ReclaimedValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("ReclaimedValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.STValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("STValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.WWValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("WWValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.WaterValve", b =>
                {
                    b.HasBaseType("RCS.Data.Entities.Valve");

                    b.HasDiscriminator().HasValue("WaterValve");
                });

            modelBuilder.Entity("RCS.Data.Entities.FigureVertex", b =>
                {
                    b.HasOne("RCS.Data.Entities.Figure", "Figure")
                        .WithMany("Vertices")
                        .HasForeignKey("FigureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RCS.Data.Entities.SurveyPoint", "Point")
                        .WithMany("FigureVertices")
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Figure");

                    b.Navigation("Point");
                });

            modelBuilder.Entity("RCS.Data.Entities.Figure", b =>
                {
                    b.Navigation("Vertices");
                });

            modelBuilder.Entity("RCS.Data.Entities.SurveyPoint", b =>
                {
                    b.Navigation("FigureVertices");
                });
#pragma warning restore 612, 618
        }
    }
}
